Dynamics plots: 2 #30
niesfutbol/hierarchical_review_plots pull request #1
Opened 2023-08-31 00:14 UTC by davidmacer

2023-08-31 00:58 UTC, nepito requested changes

2023-08-31 00:58 UTC, nepito commented on hierarchical_review_plots/polar_bar_plotly.py
> +        polar_radialaxis_dtick=20,
```suggestion
        polar_radialaxis_dtick = 20,
```

2023-09-01 00:23 UTC, nepito commented
Creo que por aquí pudiera ir el cotorreo
![image](https://github.com/niesfutbol/hierarchical_review_plots/assets/35377740/15333a0a-1d2a-431e-9217-b9e7c31564fd)
[yaxis](https://plotly.com/python/reference/layout/yaxis/)

2023-09-01 01:12 UTC, nepito commented
Así hice la revisión:
![image](https://github.com/niesfutbol/hierarchical_review_plots/assets/35377740/8e6b3a72-d3f5-447c-bc6b-d242206705e5)

2023-09-01 01:23 UTC, nepito requested changes

2023-09-01 01:23 UTC, nepito commented on hierarchical_review_plots/polar_bar_plotly.py
> +        polar_hole=0.30,
Tal vez por aquí pueda ser el cotorreo:
```suggestion
        polar_hole=0.30,
        polar = dict(
            bgcolor = "rgb(223, 223, 223)",
            angularaxis = dict(
                linewidth = 3,
                showline=True,
                linecolor='black'
            ),
        )
```
Tal vez cambiar el fondo (regresarlo a blanco) cambiar los colores de las líneas a blanco también.
De [aquí](https://plotly.com/python/polar-chart/#polar-bar-chart) lo saqué. Parece que debería de ser utilizando
`fig = go.Figure(go.Barpolar(`.

2023-09-01 21:32 UTC, nepito commented
> Creo que por aquí pudiera ir el cotorreo ![image](https://user-images.githubusercontent.com/35377740/264819706-15333a0a-1d2a-431e-9217-b9e7c31564fd.png) [yaxis](https://plotly.com/python/reference/layout/yaxis/)

No me funcionó esto tampoco.

2023-09-07 01:28 UTC, davidmacer commented
> No me funcionó esto tampoco.

También le moví un poquito por aquí y no me funcionó tampoco.

2023-09-07 03:16 UTC, nepito commented
Se ve al mero vergazo:
![image](https://github.com/niesfutbol/hierarchical_review_plots/assets/35377740/2ec8e89d-c44c-40e8-8ae5-e5017c75f8a4)

2023-09-07 03:42 UTC, nepito commented
@davidmacer [aquí](https://github.com/niesfutbol/hierarchical_review_plots/pull/1#issuecomment-1709415471) te dejé lo que encontré. Creo que ya tenemos todo. Creo que ahora es cuestión de gusto :sweat:

2023-09-15 02:07 UTC, merged

2023-09-15 02:07 UTC, nepito reviewed
Muchas gracias @davidmacer

2023-09-15 19:10 UTC, davidmacer commented
> Muchas gracias @davidmacer

A ti, @nepito. Ahí le damos a otra igual pronto.